name: jepsen
director_uuid: 44586d7c-bcce-4f5f-ae80-42bb8a1ed08b

releases:
- name: jepsen
  version: latest

compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

resource_pools:
- name: common-resource-pool
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    name: random

disk_pools:
- name: disks
  disk_size: 10_000

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.0.0/30
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2
    cloud_properties:
      name: random
  - range: 10.244.0.4/30
    reserved:
    - 10.244.0.5
    static:
    - 10.244.0.6
    cloud_properties:
      name: random
  - range: 10.244.0.8/30
    reserved:
    - 10.244.0.9
    static:
    - 10.244.0.10
    cloud_properties:
      name: random
  - range: 10.244.0.12/30
    reserved:
    - 10.244.0.13
    static:
    - 10.244.0.14
    cloud_properties:
      name: random
  - range: 10.244.0.16/30
    reserved:
    - 10.244.0.17
    static:
    - 10.244.0.18
    cloud_properties:
      name: random
  - range: 10.244.0.20/30
    reserved:
    - 10.244.0.21
    cloud_properties:
      name: random
  - range: 10.244.0.24/30
    reserved:
    - 10.244.0.25
    cloud_properties:
      name: random

jobs:
- name: control-node
  instances: 1
  templates:
    - {name: control-node, release: jepsen}
  resource_pool: common-resource-pool
  persistent_disk_pool: disks
  networks:
    - name: default
      static_ips:
        - 10.244.0.2

- name: db-node
  instances: 1
  templates:
    - {name: db-node, release: jepsen}
  resource_pool: common-resource-pool
  networks:
    - name: default
      static_ips:
        - 10.244.0.6
